// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (CheckEmailExistsRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserDetail(ctx context.Context, id pgtype.UUID) (GetUserDetailRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
